// Put courses you want in this array
module.exports = [
  'https://vueschool.io/courses/nuxtjs-fundamentals',
  'https://vueschool.io/courses/vuex-for-everyone',

  // 'https://vueschool.io/courses/the-vuejs-3-master-class',
  // 'https://vueschool.io/courses/vue-js-fundamentals-with-the-composition-api',
  // 'https://vueschool.io/courses/vuejs-3-fundamentals',
  // 'https://vueschool.io/courses/rapid-development-with-vite',
  // 'https://vueschool.io/courses/pinia-the-enjoyable-vue-store',
  // 'https://vueschool.io/courses/typescript-with-vue-js-3',
  // 'https://vueschool.io/courses/application-monitoring-in-vue-js-with-sentry',
  // 'https://vueschool.io/courses/typescript-fundamentals',
  // 'https://vueschool.io/courses/vue-router-4-for-everyone',
  // 'https://vueschool.io/courses/vueuse-for-everyone',
  // 'https://vueschool.io/courses/vue-3-single-file-components',
  // 'https://vueschool.io/courses/vue-3-composition-api',
  // 'https://vueschool.io/courses/vue-js-3-components-fundamentals',
  // 'https://vueschool.io/courses/whats-new-in-vue-3',
  // 'https://vueschool.io/courses/modern-javascript-es6-and-beyond',
  // 'https://vueschool.io/courses/reusable-vuejs-components-with-slots',
  // 'https://vueschool.io/courses/vue-apollo-graphql-fundamentals',
  // 'https://vueschool.io/courses/storybook-with-vuejs',
  // 'https://vueschool.io/courses/functional-components',
  // 'https://vueschool.io/courses/internationalization-with-vue-i18n',
  // 'https://vueschool.io/courses/learn-graphql-fundamentals',
  // 'https://vueschool.io/courses/vue-router-for-everyone',
  // 'https://vueschool.io/courses/web-accessibility-fundamentals',
  // 'https://vueschool.io/courses/vuejs-single-file-components',
  // 'https://vueschool.io/courses/learn-how-to-test-vuejs-components',
  // 'https://vueschool.io/courses/vuejs-components-fundamentals',
  // 'https://vueschool.io/courses/static-site-generation-with-nuxtjs',
  // 'https://vueschool.io/courses/async-data-with-nuxtjs',
  // 'https://vueschool.io/courses/test-with-jest',
  // 'https://vueschool.io/courses/custom-vuejs-directives',
  // 'https://vueschool.io/courses/javascript-testing-fundamentals',
  // 'https://vueschool.io/courses/dynamic-forms-vuejs',
  // 'https://vueschool.io/courses/vuejs-form-validation',
  // 'https://vueschool.io/courses/vuejs-fundamentals',
  // 'https://vueschool.io/courses/vuejs-firebase-authentication',
  // 'https://vueschool.io/courses/vuejs-firebase-realtime-database',
  // 'https://vueschool.io/courses/the-vuejs-master-class',
]
